Draft: Add Graphs as States for torchgfn
GFNOrg/torchgfn pull request #210
Opened 2024-11-06 12:43 UTC by alip67

**Description:**
Unlike the current States object that necessitates appending dummy states to batch trajectories of varying lengths, our approach aims to support Trajectories through a nested Batch object representation.  The Data class in Torch Geometric represents the graph structure, while the Batch class, which encapsulates batching of Data objects and their efficient indexing, represents the GraphStates object.

The current implementation of Trajectory supports the indexing dimensions: (Num time steps, Num trajectories, State Size). By using a nested Batch of Batch object to represent state Trajectories, the indexing would inherently take the form (Num trajectories, Num timesteps, State size). This approach requires implementing logic within `_getitem_()` and `_setitem_()` to internally. 

To Do: 
 Compatibility check with Trajectories, Transition class

2024-11-08 14:32 UTC, josephdviviano commented on src/gfn/gym/graph_building.py
> +        for i, act in enumerate(actions.tensor):
note to self - we should evaluate if this can be vectorized.

2024-11-08 14:32 UTC, josephdviviano commented on src/gfn/gym/graph_building.py
> +        for i, act in enumerate(actions.tensor):
note to self - we should evaluate if this can be vectorized.

2024-12-06 15:36 UTC, saleml commented
Thank you @younik and @alip67 for this important PR. Is there a script we can play with to see the training of the environment you created?

2024-12-06 15:40 UTC, younik commented
> Thank you @younik and @alip67 for this important PR. Is there a script we can play with to see the training of the environment you created?

There are still some issues to fix that prevent it from running properly.
I am working to fix them and will post a sample code for using it

2025-01-11 16:04 UTC, saleml reviewed
Thanks for the big PR. Here are few questions, comments, suggestions. 
I am unable to run the main script.

I don't know why CI isn't triggered in this PR.

I'd be happy to merge once the main issues are resolved, and the smaller ones defined as github issues

2025-01-11 16:04 UTC, saleml commented on tutorials/examples/test_graph_ring.py
> +class RingGraphBuilding(GraphBuilding):
I cannot run this file. I get this error
`ValueError: batch size was not specified when creating the TensorDict instance and it could not be retrieved from source.`

Can you run it?

2025-01-12 20:47 UTC, younik commented on src/gfn/gym/graph_building.py
> +    def __init__(self, num_features):
yes, good point! I remove it, this also solves the issue of dependencies

2025-01-12 20:48 UTC, younik commented on src/gfn/gym/__init__.py
> +from gfn.gym.graph_building import GraphBuilding
I remove instead torch_geometric in GraphBuilding

2025-01-12 20:49 UTC, younik commented on src/gfn/gym/__init__.py
> +from gfn.gym.graph_building import GraphBuilding
(it was used only for the graph convolution for the state_evaluator, which now it must be defined by the user)

2025-01-12 20:50 UTC, younik commented on src/gfn/gym/graph_building.py
> +        self.net = GCNConv(num_features, 1)
I removed it. It wasn't really useful anyway, it was mainly for quick testing GraphBuilding

2025-01-12 20:52 UTC, younik commented on src/gfn/containers/trajectories.py
> +        assert len(self.states.batch_shape) == 2, self.states.batch_shape
Reverted as before; it was a leftover from my debugging

2025-01-12 20:59 UTC, younik commented on pyproject.toml
> +torch_geometric = ">=2.6.0"
I removed torch_geometric from core dependencies (after removing it in GraphBuilding, see comments below). 
It is now used only for tests

2025-01-12 21:04 UTC, younik commented on src/gfn/env.py
> +        sf_tensor = self.States.make_sink_states_tensor((new_sink_states_idx.sum(),))
The reason is because of how graphs are represented in the tensor, i.e:
`tensor = TensorDict({
 'node_features': (N, F1)
 'edge_features': (M, F2)
'edge_index': (2, M)
})
`

Notice that `tensor[some_index]` doesn't make sense, and doesn't work. There is a more complex behavior defined in `GraphStates.__setitem__`, to do it correctly

2025-01-12 21:05 UTC, younik commented on src/gfn/env.py
> +        new_states[valid_states_idx] = self.States(new_not_done_states_tensor)
answered above

2025-01-12 21:16 UTC, younik commented on src/gfn/modules.py
> +        module_output: Dict[str, torch.Tensor],
Good point; I thought of TensorDict as a subclass of Dict, but that is not the case

2025-01-12 21:20 UTC, younik commented on src/gfn/gym/graph_building.py
> +        if len(actions) == 0:
`len(actions)` is supposed to be equal to `len(states)`, isn't it?
In this case, I can add an assert for this instead

2025-01-12 21:24 UTC, younik commented on src/gfn/actions.py
> +                # "edge_index": torch.zeros((2, *batch_shape, 0)),
Pardon, I changed multiple times while implementing switching between having mock values for exit action and not having them. At the moment, for exit actions you shouldn't specify features and edge_index, so I just delete this comment

2025-01-12 21:46 UTC, younik commented on src/gfn/states.py
> +        return self.tensor.device
It does if it is specified during initialization (which I always do) or `to`was used, otherwise it is None.
I thought, in principle, the components could stay in different devices, so it would make sense to stick with TensorDict semantics

2025-01-13 23:32 UTC, younik commented on src/gfn/states.py
> +
pardon, it was just a leftover; I removed it

2025-01-14 00:00 UTC, younik commented
It looks like GitHub is down, I will rerun CI tomorrow, but they are green locally

2025-01-14 00:05 UTC, younik commented on src/gfn/actions.py
> +        compare = torch.all(self.tensor == other.tensor, dim=-1)
Correct, nice catch! I need to add a test for all these action features

2025-01-14 10:25 UTC, younik commented on tutorials/examples/test_graph_ring.py
> +class RingGraphBuilding(GraphBuilding):
Yes, I can run it...
Which version of TensorDict are you using? I have `0.6.2`

2025-01-14 10:27 UTC, younik commented on src/gfn/modules.py
> +        dists["features"] = Normal(module_output["features"], temperature)
What do you mean by invalid features?

In case the action is an EXIT action, these features are ignored... but otherwise, I don't see any invalid feature(?)

2025-01-14 10:44 UTC, younik commented on src/gfn/utils/distributions.py
> +    """A mixture distribution."""
It is a dictionary of distributions; which is the same as CompositeDistribution in tensordict (the TODO wanted to say "remove it in favor of CompositeDistrtribution"). The reason why I didn't use CompositeDistribution is that I needed a total log_probs (instead of a dictionary of log probs). 

I updated the TODO to be clearer. I plan to do it with a wrapper around CompositeDistribution (or extending it).

2025-01-14 10:49 UTC, younik commented on src/gfn/utils/distributions.py
> +class CategoricalActionType(Categorical):  # TODO: remove, just to sample 1 action_type
This is used in the GraphActionPolicyEstimator.
I plan to remove it after the first round of reviews (if it doesn't change the code too much) or in a following PR. (Same for the other TODO).

This is because this PR was becoming complex very fast (as you may have noticed while reviewing 😅), so I tried to avoid some not-strictly-necessary features.

2025-01-14 11:23 UTC, saleml commented on src/gfn/gym/graph_building.py
> -
I forgot whether I left a comment on this here or not. So it's not needed after all ?

2025-01-14 11:28 UTC, younik commented on src/gfn/gym/graph_building.py
> -
No, it was just a mock default evaluator (nn to compute reward from states).
But it wouldn't be helpful for any user-case, it was just for easy testing GraphBuilding. 
I expect the user wants to always define the evaluator

2025-01-14 22:50 UTC, younik commented on src/gfn/modules.py
> +        dists["features"] = Normal(module_output["features"], temperature)
@saleml we may need to mask the invalid `edge_index` indeed.
At the moment:
  - GraphBuilding env requires the edge doesn't exist (no multiple edges from & to the same node). This is because it is then easier for backward_step (removing the edge).
  - There is no real masking for it, so the Estimator can sample an invalid action 
  
 This is the reason tests in CI are failing. Two solutions I can see:
 **1) Add mask in the estimator (the code you commented here)**
This is easy to do, but is it general enough that multiple edges are not allowed? 
Also, I already wanted to raise that we have `forward_mask` and `backward_mask` in States, while also having `isActionValid` method. This is a repetition of code (and now we would add another repetition here).

**2) Allow GraphBuilding to have multiple same edges** 
We need to use the edge features to check which edge to remove in the backward step.

What do you think?

2025-01-14 22:58 UTC, younik commented on src/gfn/env.py
> +        self.sf = sf
If we want to support this case, I suggest doing it in another PR

2025-01-14 23:23 UTC, younik commented on src/gfn/modules.py
> +        if states.tensor["node_feature"].shape[0] > 1 and torch.any(edge_index_logits != -float("inf")):
At the moment, all the nets return the same action type, so this works, however, you are right, this is not general,.
I restrict to this case because when the number of nodes varies across the batch, also the outputs of the nets vary (e.g. for one batch you will have probs of (N1, N1) for edge_indexes and the other (N2, N2) breaking batching.

I am not sure how to overcome this problem while being reasonably efficient.

> BTW this might also need to handle masks for valid edges
Perfectly right, this is the reason for CI failing; see the other comment

2025-01-14 23:30 UTC, younik commented on src/gfn/gflownet/flow_matching.py
> +        # if not env.is_discrete:
Yes, I am using FM for the ring example. In that case, the actions are discrete (you have a fixed number of nodes, and there is only "add edge" action).
So I override the is_discrete in `RingGraphBuilding`, and restored the check in FM.

2025-01-15 16:43 UTC, younik commented on src/gfn/actions.py
> +    def stack(cls, actions_list: list[GraphActions]) -> GraphActions:
Surprisingly, it works because TensorDict support common operations like `torch.stack` and `torch.extend`. This method was actually the same as the one implemented in the superclass Actions, so I just removed it. I realized there is no tests for Actions class, so I added it in the last commit.

2025-01-15 16:43 UTC, younik commented on src/gfn/actions.py
> +
> Surprisingly, it works because TensorDict support common operations like `torch.stack` and `torch.extend`. This method was actually the same as the one implemented in the superclass Actions, so I just removed it. I realized there is no tests for Actions class, so I added it in the last commit.

See comment regarding stack

2025-01-15 17:29 UTC, saleml commented on src/gfn/actions.py
> +    def stack(cls, actions_list: list[GraphActions]) -> GraphActions:
Noted! Thanks for the tests

2025-01-15 17:44 UTC, saleml commented on src/gfn/modules.py
> +        dists["features"] = Normal(module_output["features"], temperature)
I suggest adding basic edge masking in the estimator for now to fix the CI, but we should create a follow-up issue to properly consolidate all action validation logic into the States class. This will eliminate code duplication and provide a single source of truth for action validity. The States class should be responsible for providing comprehensive masks that cover both action types and edge validity.
This approach:
- Gets CI passing quickly
- Acknowledges the technical debt
- Sets a clear path forward
- Keeps the current PR scope manageable

SO

Short-term fix (for this PR):
- Go with solution #1 (add masking in the estimator) as a temporary fix to get CI passing
- Add a TODO/issue comment indicating this is temporary
- Document the current limitation in the docstring
Long-term solution (next PR):
- Consolidate all action validation logic into the States class (solution #2)
- The States class should provide comprehensive masks that include:
1. Action type validity (current implementation)
2. Edge validity (currently missing)
3. Any other environment-specific constraints

LMK what you think

2025-01-15 17:48 UTC, saleml commented on tutorials/examples/test_graph_ring.py
> +class RingGraphBuilding(GraphBuilding):
```
ERROR: Could not find a version that satisfies the requirement tensordict==0.6.2 (from versions: 0.0.1a0, 0.0.1b0, 0.0.1rc0, 0.0.2a0, 0.0.2b0, 0.0.3, 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2)
ERROR: No matching distribution found for tensordict==0.6.2
```

Althout in their github repo there is a 0.6.2 release. I will try to debug this.

2025-01-15 22:59 UTC, younik commented on src/gfn/modules.py
> +        dists["features"] = Normal(module_output["features"], temperature)
Sounds good!

Actually, if I make the States masks comprehensive, then I should able to just use them in the estimator for masking (so solution 2).

I will do it soon!

2025-01-15 23:19 UTC, younik commented on src/gfn/modules.py
> +        self.is_backward = is_backward
Good point. I removed it because the IdentityProcessor doesn't work with TensorDict.
I just fixed it by making a default Processor in `GraphActionPolicyEstimator` (see [this commit](https://github.com/alip67/torchgfn/commit/4ee6987f41678dd4ffe188693ec16e554f894f9e)).
However, I had to put a mock value in output_dim (I used -1); which is pretty ugly, we should review that as well.

2025-01-15 23:20 UTC, younik commented on src/gfn/modules.py
> +        self.is_backward = is_backward
(I added a TODO there as well)

2025-01-15 23:30 UTC, younik commented on src/gfn/modules.py
> -        self._output_dim_is_checked = False
I removed the check on the parent class `GFNModule`as it didn't work with `GraphActionPolicyEstimator` (TensorDict shape is only the "batch shape").
But I added the checks on the subclasses

2025-01-16 23:57 UTC, josephdviviano requested changes
First pass at a review. Thanks so much for your amazing work. I am going to mess around with the test cases and environment next to get a better understanding of how things function together. In the meantime, I have some questions.

2025-01-16 23:57 UTC, josephdviviano commented on src/gfn/gym/graph_building.py
> +        state_tensor = deepcopy(states.tensor)
ditto RE: `deepcopy`.

2025-01-16 23:57 UTC, josephdviviano commented on src/gfn/gym/graph_building.py
> +            edge_mask_0 = modified_dict["edge_index"][:, 0] >= end_ptr
What does "after the current graph" mean here?

2025-01-16 23:57 UTC, josephdviviano commented on src/gfn/gym/graph_building.py
> +            modified_dict["edge_index"][edge_mask_1, 1] += shift
I think this looks right. This is note to self to ensure we have solid tests on this logic (and the backward step of removing).

2025-01-16 23:57 UTC, josephdviviano commented on src/gfn/modules.py
> -        self._output_dim_is_checked = False
Is there no way to check the output dim of a `TensorDict`? Seems like it should be accessible in the `features` field no?

2025-01-16 23:57 UTC, josephdviviano commented on src/gfn/modules.py
> -        out = self.module(input)
It's a shame to remove all this from the base class and have to re-implement it in the all of the classes that inherit from this one.

Is this only because of `self._output_dim_is_checked` or is there more?

2025-01-16 23:57 UTC, josephdviviano commented on src/gfn/modules.py
> -    @property
Ditto

2025-01-16 23:57 UTC, josephdviviano commented on src/gfn/modules.py
> -    def expected_output_dim(self) -> int:
Ditto

2025-01-16 23:57 UTC, josephdviviano commented on src/gfn/modules.py
> +        assert out.shape[-1] == 1
This also seems like a much harder constraint.

2025-01-16 23:57 UTC, josephdviviano commented on src/gfn/modules.py
> +        dists["features"] = Normal(module_output["features"], temperature)
I disagree that we should fix it here (i.e., in the `Estimator`), or if we do so, we should implement masking properly in the `States` class before the release of V2 because this is a clear design pattern violation.

There is no problem adding multiple edges to-from the same node in principle (in say, a multi-attribute graph) but that does make things way more complex, and I think we can safely avoid that complexity here, as single edges to-from the same nodes will cover a lot of AI for Science applications in the near term.

2025-01-16 23:57 UTC, josephdviviano commented on src/gfn/samplers.py
>              if save_logprobs:
Wait, why are we removing this flag?

2025-01-16 23:57 UTC, josephdviviano commented on src/gfn/states.py
> +        }
Would it be better to say that the `TensorDict` should *only* contain the required keys?

2025-01-16 23:57 UTC, josephdviviano commented on src/gfn/utils/distributions.py
> +    """A mixture distribution."""
To @saleml 's point, though, you're returning the `sum(log_probs)` across the mixture, which implies they all have equal weight (uniform) - perhaps this should be made explicit?

2025-01-17 06:15 UTC, saleml commented on src/gfn/samplers.py
>              if save_logprobs:
It just moved 4 lines below

2025-01-17 12:51 UTC, younik commented on src/gfn/modules.py
> +        dists["features"] = Normal(module_output["features"], temperature)
Yes, I am trying to implement the complete forward/backward mask in states.

I have the following problem:
In general, the number of nodes for each graph can vary. The mask for edge_index is (B, N, N), where N is the number of nodes. However, the number of nodes varies across batch...

Two possible solutions:
1) Use (B, N, N), with N the total number of nodes (not in one graph, but across the graphes in the batch). This is more memory consuming, but general.
2) Enforce the number of nodes to be the same across the batch, which means enforcing the action to be the same across the batch (you cannot add a node to one graph while adding an edge to another).

2025-01-19 21:48 UTC, younik commented on pyproject.toml
> +torch_geometric = { version = "*", optional = true }
I added >=2.6.1, which is the one I am using

2025-01-19 21:50 UTC, younik commented on src/gfn/actions.py
> +        self.tensor[index] = action.tensor
It is a batch of actions, but it is agnostic to trajectories, and it doesn't need `trajectory_len`

2025-01-19 21:53 UTC, younik commented on src/gfn/actions.py
> +        compare = torch.all(self.tensor == other.tensor, dim=-1)
Yes, as the tensor is
```
{'action_type': (B, 1),
'features': (N, F),
'edge_index': (M, 2)}
```

And after `torch.all`, becomes:

```
{'action_type': (B,),
'features': (N,),
'edge_index': (M,)}
```

2025-01-19 21:59 UTC, younik commented on src/gfn/gym/graph_building.py
> +        state_tensor = deepcopy(states.tensor)
Good point, I thought this was the behavior of other envs as well, but it is not.
I removed it

2025-01-19 22:02 UTC, younik commented on src/gfn/gym/graph_building.py
> +            modified_dict["edge_index"][edge_mask_1, 1] += shift
Yes, the test_graph_env in test_environments is supposed to smoke test this as well

2025-01-19 22:05 UTC, younik commented on src/gfn/gym/graph_building.py
> +            edge_mask_0 = modified_dict["edge_index"][:, 0] >= end_ptr
Graphs states are saved in batches, i.e.
state = {
'node_features': (N, F)
'edge_indices': (M, 2)
batch_ptr: (B + 1,)
...
}

represent B graphs. When you add a node to graph `i` you must be sure to increase the edge_indices for every node in graphs after the batch `i`, so they represent the correct edges.

2025-01-19 22:38 UTC, younik commented on src/gfn/states.py
> +        }
I think a user may want to implement their GraphStates, which may have additional keys.
I don't see relevant drawbacks in allowing other keys to eventually be there

2025-01-20 21:06 UTC, younik commented on src/gfn/modules.py
> -        self._output_dim_is_checked = False
Yes, you can use `features` but the check code will be different for `GraphActionPolicyEstimator` (as you need to ask for "features"), so you need to implement it in the subclass

2025-01-20 21:10 UTC, younik commented on src/gfn/modules.py
> -        out = self.module(input)
Yes, I am not checking output here, but in the subclasses (`sel.module` is still called below of course)

2025-01-20 21:13 UTC, younik commented on src/gfn/modules.py
> +        assert out.shape[-1] == 1
Why? The `expected_output_dim` is 1 in this class, so it seems the same to me (actually softer as I don't check the dtype).

2025-01-20 21:30 UTC, younik commented on src/gfn/utils/distributions.py
> +    """A mixture distribution."""
Oh, got it, I added a comment

2025-01-21 07:12 UTC, saleml commented on pyproject.toml
tensordict = ">=0.6.1" does not work
basically, you have to install tensordict-nightly if using pip, or install from source if using the tensordict repo

2025-01-21 14:02 UTC, saleml commented on pyproject.toml
It's ok actually. my conda was broken. Now it finds tensordict 0.6.1

2025-01-24 18:35 UTC, josephdviviano commented on src/gfn/states.py
> +        }
Good point!

2025-01-24 18:38 UTC, josephdviviano commented on src/gfn/actions.py
> +        self.tensor[index] = action.tensor
right of course, my apologies.

2025-01-24 18:40 UTC, josephdviviano commented on src/gfn/gym/graph_building.py
> +            edge_mask_0 = modified_dict["edge_index"][:, 0] >= end_ptr
Thanks -- I think perhaps more comments in the code would be helpful to ensure everyone is on the same page as to what is going on here (including future contributors).

2025-01-24 18:42 UTC, josephdviviano commented on src/gfn/modules.py
> -        out = self.module(input)
@younik I'm not super comfortable with this change. We've had output checks living at the `gfn/modules.py` for a long time now. Moving that into the estimators does not make sense to me - and seems unrelated to the goal of adding graphs as states into the library.

To me, this really seems like the most abstract place to have such a check. Why do we want to move it out of here? Tagging @saleml for the discussion.

2025-01-24 18:53 UTC, younik commented on src/gfn/modules.py
> -        out = self.module(input)
I removed because the line `module_output.shape[-1] != self.expected_output_dim()` throw an error when module_output is a tensordict.

Oh, maybe I see it now, are you suggesting to override the `check_output_dim` method in `GraphActionPolicyEstimator` ?

2025-01-24 20:56 UTC, josephdviviano commented on src/gfn/modules.py
> -        out = self.module(input)
Yeah, since this `check_output_dim` check needs to be handled as a special case for `GraphActionPolicyEstimator` -- but I'm open to the discussion.

2025-01-24 23:13 UTC, younik commented on src/gfn/modules.py
> -        out = self.module(input)
Overriding `check_output_dim`sounds good!

2025-02-10 13:04 UTC, younik commented on src/gfn/gflownet/flow_matching.py
> +        # ), "logF must be a DiscretePolicyEstimator or ConditionalDiscretePolicyEstimator"
I removed it

2025-02-13 09:20 UTC, hyeok9855 reviewed
Thank you for you're hard work!

2025-02-13 09:20 UTC, hyeok9855 commented on src/gfn/states.py
> +        return cls(tensor)
Can we just use the method from the parent class?

2025-02-13 09:20 UTC, hyeok9855 commented on src/gfn/states.py
> +        batch_shape = batch_shape if isinstance(batch_shape, Tuple) else (batch_shape,)
Why not allow Tuple only?

2025-02-19 14:10 UTC, saleml commented on tutorials/examples/train_graph_ring.py
> +    def __init__(self, n_nodes: int, state_evaluator: callable, directed: bool):
for me, it doesn't make sense to subclass GraphBuilding without using it's init function

2025-02-19 14:12 UTC, saleml commented on tutorials/examples/train_graph_ring.py
> +    def __init__(self, n_nodes: int, state_evaluator: callable, directed: bool):
my bad

2025-02-20 15:34 UTC, younik commented on src/gfn/states.py
> +        self.tensor["batch_shape"] = self.tensor["batch_shape"] + other.tensor["batch_shape"]
The problem is with these lines.

When you extend a tensor, you should only sum the first dimension.
Imagine with tensors, if you do
(10, 200) . extends (30, 200) you should get (40, 200) not (40, 400)

However, this will throw an error if you try to extend (0, 0) with (30, 200) because 0 != 200, but I believe this is expected and should be changed above in the stack trace

2025-02-23 11:41 UTC, saleml commented
Thanks @josephdviviano for the fix. I have merged master into this. There are a few tests that still fail. I did not try to solve them as I'm still not sure whether you or @younik are planning more major changes to this branch?

Also, as mention in #245 , I'd like it if we merge that one first, and have all the safety features here as well before merging :)

2025-02-23 12:53 UTC, josephdviviano commented
Note that I'm still not totally satisfied with this PR , but agree we
should start merging master into this.

It's still very hard to train a 4 node directed graph

Joseph (Mobile)


On Sun, Feb 23, 2025 at 06:42 saleml ***@***.***> wrote:

> Thanks @josephdviviano <https://github.com/josephdviviano> for the fix. I
> have merged master into this. There are a few tests that still fail. I did
> not try to solve them as I'm still not sure whether you or @younik
> <https://github.com/younik> are planning more major changes to this
> branch?
>
> Also, as mention in #245 <https://github.com/GFNOrg/torchgfn/pull/245> ,
> I'd like it if we merge that one first, and have all the safety features
> here as well before merging :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GFNOrg/torchgfn/pull/210#issuecomment-2676805312>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7TL2WPS24B6VYIM3R4WYL2RGXYXAVCNFSM6AAAAABRIYBDROVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNZWHAYDKMZRGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
> [image: saleml]*saleml* left a comment (GFNOrg/torchgfn#210)
> <https://github.com/GFNOrg/torchgfn/pull/210#issuecomment-2676805312>
>
> Thanks @josephdviviano <https://github.com/josephdviviano> for the fix. I
> have merged master into this. There are a few tests that still fail. I did
> not try to solve them as I'm still not sure whether you or @younik
> <https://github.com/younik> are planning more major changes to this
> branch?
>
> Also, as mention in #245 <https://github.com/GFNOrg/torchgfn/pull/245> ,
> I'd like it if we merge that one first, and have all the safety features
> here as well before merging :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GFNOrg/torchgfn/pull/210#issuecomment-2676805312>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7TL2WPS24B6VYIM3R4WYL2RGXYXAVCNFSM6AAAAABRIYBDROVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNZWHAYDKMZRGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-03-04 13:06 UTC, josephdviviano commented
Due to some outstanding confusion RE forks of forks, @hyeok9855 and I moved all of the forks to branches of the main repo. This will be merged and a new PR opened from there (this discussion will be referenced).

2025-03-04 13:07 UTC, josephdviviano commented on src/gfn/states.py
> +        self.tensor["batch_shape"] = self.tensor["batch_shape"] + other.tensor["batch_shape"]
This is resolved (with the move to PYG).

2025-03-04 13:10 UTC, josephdviviano commented on tutorials/examples/train_graph_ring.py
> +                self._log_rewards: Optional[float] = None
fixed.

2025-03-04 13:11 UTC, josephdviviano commented on tutorials/examples/train_graph_ring.py
> +                {
rendered irrelevant by pyg move

2025-03-04 13:12 UTC, josephdviviano commented on tutorials/examples/train_graph_ring.py
> +        super().__init__(feature_dim=n_nodes, state_evaluator=state_evaluator)
it's `n_nodes` because the `n x n` graph is computed using an inner product which is `n_nodes x embedding_dim`.

2025-03-04 13:12 UTC, josephdviviano commented on src/gfn/gym/graph_building.py
> +        state_evaluator: Callable that computes rewards for final states.
renamed.

2025-03-04 13:13 UTC, josephdviviano commented on src/gfn/states.py
> +        batch_shape = batch_shape if isinstance(batch_shape, Tuple) else (batch_shape,)
I think it's ok like this.

2025-03-04 13:51 UTC, josephdviviano commented on src/gfn/states.py
> +        return cls(tensor)
Agreed. Removed.

2025-03-04 13:54 UTC, josephdviviano commented on src/gfn/env.py
> +        self.is_discrete = False
Looks like it's already set correctly in the parent class.

2025-03-04 13:58 UTC, merged